name: foody_online_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  lottie: ^1.0.1
  cloud_firestore: ^0.16.0
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  modal_progress_hud: ^0.1.3
  flutter_spinkit: ^4.1.2
  provider: ^4.3.3
  flutter_slidable: ^0.5.7
  toast: ^0.1.5
  rflutter_alert: ^1.1.0
  page_transition: ^1.1.7+6
  google_maps_flutter: ^2.0.1
  geolocator: ^6.1.6
  geocoder: ^0.2.1
  font_awesome_flutter: ^8.12.0
  eva_icons_flutter: ^2.0.1
  flutter_easyloading: ^2.2.2
  chips_choice: ^2.0.1
  url_launcher: ^6.0.4
  map_launcher: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/
    - animation/
  fonts:
    - family: Pacifico
      fonts:
        - asset: Font/Pacifico-Regular.ttf
